### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by mtrudel** [twooster/strap#2]
@twooster I'm wondering if you're still willing to take PRs / release hex packages against this repo? I ask because I've added support for M1 / M2 creation on top of Strap and I'd love to include it in the library. However, since I'm using Strap as a dependency for a hex package I'm authoring and  mix requires that all transitive dependencies be published hex packages, it's a dead end working up a PR if it isn't going to get published. Hoping for confirmation before I work it up into a PR.

Thanks!

**Comment by twooster** [comment]
Hi @mtrudel I'd be willing to take PRs and release hex packages, but I suppose the project was kind of on life support. It was a test project for me to learn some Elixir. :) Send a PR and I'll get it merged.

**Comment by mtrudel** [comment]
Sounds great. I'll get my project code factored into Strap and push up a PR, hopefully over the weekend.
